# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mean1 <- function(x) {
    .Call('EflowStats_mean1', PACKAGE = 'EflowStats', x)
}

rle2 <- function(x) {
    .Call('EflowStats_rle2', PACKAGE = 'EflowStats', x)
}

var1 <- function(x) {
    .Call('EflowStats_var1', PACKAGE = 'EflowStats', x)
}

var2 <- function(x) {
    .Call('EflowStats_var2', PACKAGE = 'EflowStats', x)
}

